config/routes.rb
Rails.application.routes.draw do
  resources :game do
    resources :responses do
      resources :options
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
end

app/models/response.rb
class Response < ApplicationRecord
  has_many :options
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def index
    @current_response = Response.first
    @current_options = Option.where(response_id: @current_response.id)
  end

  def show
    @current_response = Response.find(get_next_id)
    @current_options = Option.where(response_id: @current_response.id)
  end

  private
  def get_next_id
    Option.find(params[:id]).next_response_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/game/index.html.erb
<h1>Welcome to Adventure Bot. When ready, click below to start you journey.</h1>
<%= button_to 'Begin Adventure', game_responses_url(1), method: 'get'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdventureBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/options/index.html.erb
<% if Option.all.any? %>
  <% Option.all.each do |option| %>
    <h2><%= option.message %></h2>
  <% end %>
<% else %>
  <h1>No options yet</h1>
<% end %>

app/views/responses/index.html.erb
<% if Response.all.any? %>
  <% Response.all.each do |response| %>
    <h2><%= response.message %></h2>
  <% end %>
<% else %>
  <h1>No responses yet</h1>
<% end %>

app/views/responses/show.html.erb
<h2><%= @current_response.message %></h2>

<% @current_options.all.each do |option| %>
  <%= button_to option.message, game_response_path(1, option), method: 'get' %>
<% end %>

<% if @current_response.result == 'fail' %>
  <%= button_to 'Unlucky! Fancy another go?', game_index_url, method: 'get'%>
<% elsif @current_response.result == 'pass' %>
  <%= button_to 'Nicely done! Replay?', game_index_url, method: 'get'%>
<% end %>